<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Empo.ApiGateway-b2530e76-7bc5-4933-ba86-e046a386e4c2</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
    <PackageReference Include="Ocelot" Version="24.0.0" />
    <PackageReference Include="Ocelot.Provider.Consul" Version="24.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Empo.Shared.Utility\Empo.Shared.Utility.csproj" />
  </ItemGroup>

</Project>
