// <auto-generated />
using System;
using Empo.EmployeeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Empo.EmployeeService.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20260822074317_EmployeeMigration6")]
    partial class EmployeeMigration6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employee")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Branch.BranchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Branch", "employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.CommonEntity.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.ToTable("Address", "employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f45a845-485c-41c6-a2e8-ede512c2cba5"),
                            Address1 = "22k/5b",
                            Address2 = "Kareli",
                            City = "Prayagraj",
                            Country = "India",
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            State = "UP",
                            ZipCode = "211016"
                        });
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Department.DepartmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Department", "employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Designation.DesignationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Designation", "employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeAttendanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClockInDevice")
                        .HasColumnType("text");

                    b.Property<string>("ClockInIP")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("ClockInTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ClockOutDevice")
                        .HasColumnType("text");

                    b.Property<string>("ClockOutIP")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("ClockOutTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("WorkedHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendence", "employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DesignationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EmployeeRole")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.ToTable("Employee", "employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31f29e8c-1ccb-400b-99f8-9d03194ebc23"),
                            AddressId = new Guid("0f45a845-485c-41c6-a2e8-ede512c2cba5"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 2, 1),
                            Email = "alirizvi9721@gmail.com",
                            EmployeeRole = 1,
                            FirstName = "Mohd",
                            IsActive = true,
                            LastName = "Ali Rizvi",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeePhoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Phone", "employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Permission", "employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e01e7324-2d10-45ed-b8b7-a15ced9320c5"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employee Permission",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Employee.Create"
                        },
                        new
                        {
                            Id = new Guid("7845a4bc-aebb-4627-b307-558342fab6b5"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employee Permission",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Employee.Get"
                        },
                        new
                        {
                            Id = new Guid("8be3f794-30f4-485d-907a-78f389884cda"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employee Permission",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Employee.Update"
                        },
                        new
                        {
                            Id = new Guid("f5079067-b225-4a2f-a876-ce01cc41f6cf"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employee Permission",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Employee.List"
                        });
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", "employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Role", "employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4b49093-ab55-47a2-91ef-1681372c7e6c"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full access",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("eaaf0947-b11c-4c4c-ad36-66facc063803"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Partial access",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("30f6262e-0b43-481a-a284-3f060c924525"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Department based access",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("364b4583-c5cf-468e-a269-fbef8e683738"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "self service access",
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.Role_PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Role_Permission", "employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("812a175a-4342-44cb-95c4-11914d3038eb"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PermissionId = new Guid("e01e7324-2d10-45ed-b8b7-a15ced9320c5"),
                            RoleId = new Guid("e4b49093-ab55-47a2-91ef-1681372c7e6c")
                        },
                        new
                        {
                            Id = new Guid("0a396c94-6ded-4a69-a472-8c8968a957b1"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PermissionId = new Guid("7845a4bc-aebb-4627-b307-558342fab6b5"),
                            RoleId = new Guid("e4b49093-ab55-47a2-91ef-1681372c7e6c")
                        },
                        new
                        {
                            Id = new Guid("a127cfbf-7643-4905-b5b1-0a2cb6766cd1"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PermissionId = new Guid("8be3f794-30f4-485d-907a-78f389884cda"),
                            RoleId = new Guid("e4b49093-ab55-47a2-91ef-1681372c7e6c")
                        },
                        new
                        {
                            Id = new Guid("b759aee7-aeb8-429c-ac1a-31e203c38c96"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PermissionId = new Guid("f5079067-b225-4a2f-a876-ce01cc41f6cf"),
                            RoleId = new Guid("e4b49093-ab55-47a2-91ef-1681372c7e6c")
                        });
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifieed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            CreatedBy = new Guid("c0138cd8-98c8-44c1-aa79-ac489e57d1b5"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModifieed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@empo.com",
                            EmailConfirmed = true,
                            EmployeeId = new Guid("31f29e8c-1ccb-400b-99f8-9d03194ebc23"),
                            IsActive = true,
                            LastLoginAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PasswordHash = "$2a$12$GHDrilbduUGPyqdyNMuueOz2ervhawUXCCkF32Ve2.Ezpq2M2yuga",
                            PhoneNumber = "9721974817",
                            PhoneNumberConfirmed = true,
                            RoleId = new Guid("e4b49093-ab55-47a2-91ef-1681372c7e6c"),
                            UserName = "admin1"
                        });
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Branch.BranchEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.CommonEntity.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeAttendanceEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeEntity", "Employee")
                        .WithMany("Attendance")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.CommonEntity.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.Branch.BranchEntity", "Branch")
                        .WithMany("BranchEmployee")
                        .HasForeignKey("BranchId");

                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.Department.DepartmentEntity", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.Designation.DesignationEntity", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId");

                    b.Navigation("Address");

                    b.Navigation("Branch");

                    b.Navigation("Department");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeePhoneEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeEntity", "Employee")
                        .WithOne("Phone")
                        .HasForeignKey("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeePhoneEntity", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.RefreshTokenEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.Role_PermissionEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.User.PermissionEntity", "Permission")
                        .WithMany("RolePermission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.User.RoleEntity", "Role")
                        .WithMany("Role_Permission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.UserEntity", b =>
                {
                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Empo.EmployeeService.Infrastructure.Data.Entities.User.RoleEntity", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Branch.BranchEntity", b =>
                {
                    b.Navigation("BranchEmployee");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Department.DepartmentEntity", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Designation.DesignationEntity", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.Employee.EmployeeEntity", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.PermissionEntity", b =>
                {
                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Empo.EmployeeService.Infrastructure.Data.Entities.User.RoleEntity", b =>
                {
                    b.Navigation("Role_Permission");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
